**PyTorch** is basically an extension of Numpy, numerical library of python. Numpy arrays can't utilise GPUs, but pytorch Tensors can. This makes them faster for performing calculations and are thus extensively used for Deep Learning Models.

Also pytorch is more ***pythonic*** compared to other deep learning frameworks
as it is defined-by-run and supports dynamic graph. It is very flexible and integrates flawlessly with other scientific libraries in python such as Scikit-Learn, Numpy and Matplotlib.

In [0]:
import torch

In [3]:
# zeros
a = torch.zeros(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
# ones
b = torch.ones(3,4)
b

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [5]:
# dtype
print(a.dtype)
print(b.dtype)

torch.float32
torch.float32


- default datatype is float32

In [6]:
# both return same
print(a.shape)
print(a.size())

torch.Size([2, 3])
torch.Size([2, 3])


In [10]:
# initialising a double tensor
c = torch.DoubleTensor([[1,2,3],[4,5,6]])
c.dtype

torch.float64

- float64 means more precision

In [11]:
print(c.mean())
print(c.std())  # standard deviation

tensor(3.5000, dtype=torch.float64)
tensor(1.8708, dtype=torch.float64)


In [15]:
# initialsing a tensor on gpu
d = torch.tensor([[1,2,3],[4,5,6]], device='cuda' if torch.cuda.is_available() else 'cpu')
print(d)
print(d.device)

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')
cuda:0


- Hence it is on Cuda (Nvidia GPU). Also that 0 denotes it's on the first GPU.

In [16]:
# reshaping a tensor using view
print(b.shape)
b = b.view(4,3)
print(b.shape)

torch.Size([3, 4])
torch.Size([4, 3])


In [18]:
# reshaping a tesnor using reshape
print(b.shape)
b = b.reshape(3,4)
print(b.shape)

torch.Size([4, 3])
torch.Size([3, 4])


- pytorch by default treats the dimension of 3-D tensors as ***(channel, Height, width)***.

In [22]:
# random tensor in torch, each value is in between 0 and 1
r1 = torch.rand((4,4), dtype=torch.float)
print(r1.dtype)

torch.float32


In [58]:
# random tensor with normal distribution, i.e mean = 0 and variance 1
# the values belong to -infinity and infinity
r2 = torch.randn((4,4), device='cuda') 
print(r2)
print(r2.mean())

tensor([[-0.7287,  0.1141, -1.0599, -0.9317],
        [-0.6752,  1.3931, -0.9183, -0.6202],
        [-0.4702, -2.4342,  0.0434, -1.8054],
        [ 1.0517,  2.3745, -0.2207,  0.0520]], device='cuda:0')
tensor(-0.3022, device='cuda:0')


#### Difference between rand and randn
Results of generating 1000000 samples.

![](https://qphs.fs.quoracdn.net/main-qimg-c959937e8eeb7892dc7f76afb225c271)
![](https://qphs.fs.quoracdn.net/main-qimg-60ba791fed295fd9b06939bb63e274f8)

In [29]:
# generating tensor with random integers in between a and b
i = torch.randint(0,5, (2,2), device='cuda')
print(i.dtype)
print(i)

torch.int64
tensor([[1, 1],
        [2, 0]], device='cuda:0')


In [30]:
# Get the number of elements
print(torch.numel(i))

4


In [41]:
# Get the sclar value from a tensor with one element
k = torch.tensor([2])
print(k.shape)
k_value = k.item()   # item()
print(k_value)
print(type(k_value))

torch.Size([1])
2
<class 'int'>


In [42]:
# initialise a tensor with shape equalt to another tensor's shape
r2_like = torch.rand_like(r2, dtype=torch.double)
print(r2.shape)
print(r2_like.shape)
print(r2_like.dtype)

torch.Size([4, 4])
torch.Size([4, 4])
torch.float64


### operations

In [47]:
def add(a,b):
    r3 = None
    if a.device == b.device:
        if a.shape == b.shape:
            r3 = torch.add(r2, r1)  # need to 
    return r3    
r3 = add(r1, r2)
print(r3)

None


In [51]:
# le't check
print(r1.device)
print(r2.device)

cpu
cuda:0


In [59]:
# gotcha, transfer r1 to gpu
r1 = r1.to(device='cuda')
r3 = add(r1, r2)
print(r3)

tensor([[-0.4928,  0.9808, -0.5023, -0.4091],
        [-0.1903,  1.7401, -0.9022,  0.0090],
        [ 0.2297, -2.0197,  0.3482, -1.2343],
        [ 1.7424,  2.5603,  0.3039,  0.4817]], device='cuda:0')


In [62]:
# in-place addition
r2.add_(r1)  # r2 = torch.add(r2,r1)
print(r2)
print(r2 == r3)

tensor([[-0.4928,  0.9808, -0.5023, -0.4091],
        [-0.1903,  1.7401, -0.9022,  0.0090],
        [ 0.2297, -2.0197,  0.3482, -1.2343],
        [ 1.7424,  2.5603,  0.3039,  0.4817]], device='cuda:0')
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], device='cuda:0', dtype=torch.uint8)


In [65]:
# dot product
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])
dot_1 = torch.dot(x,y)    # torch.dot()
dot_2 = torch.sum(torch.mul(x,y))    # torch.mul()
print(dot_1)
print(dot_2)

tensor(32)
tensor(32)
